-- For User Table
CREATE TABLE [USER](
    [USER_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_USER PRIMARY KEY,
    [USER_NAME] [nvarchar](50) NOT NULL, -- "Because French name" ~ Huzaifah
    [USER_DOB] [datetime] NULL,
	[FK_JOB_ROLE_ID] [int] NULL,
	[USER_EMAIL] [varchar](100) NOT NULL,
	[USER_PASSWORD] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For Transactions Table
CREATE TABLE [TRANSACTION] (
	[TRANSACTION_ID] [int] IDENTITY(1000,1) NOT NULL CONSTRAINT PK_TRANSACTION PRIMARY KEY,
	[FK_PAYMENT_METHOD_ID] [int] NULL,
	[FK_ACCOUNT_ID] [int] NULL,
	[FK_EXPENSE_ID] [int] NULL,
	[TRANSACTION_DATE] [datetime] NOT NULL,
	[FK_CREATED_BY] [int] NULL,
	[TRANSACTION_AMOUNT] [money] NOT NULL,
	[FK_LAST_UPDATED_BY] [int] NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For Account 
CREATE TABLE [ACCOUNT] (
	[ACCOUNT_ID] [int] IDENTITY(1000,1) NOT NULL CONSTRAINT PK_ACCOUNT PRIMARY KEY,
	[ACCOUNT_TITLE] [nvarchar](50) NOT NULL, -- Because French Name -> or bhi hote hain
	[ACCOUNT_NUM] [varchar](34) NOT NULL -- As per international standards
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For UserAccount Bridge Table
CREATE TABLE [USER_ACCOUNT] (
	[FK_ACCOUNT_ID] [int] NOT NULL,
	[FK_USER_ID] [int] NOT NULL,
	CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY ([FK_ACCOUNT_ID], [FK_USER_ID])
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For JobRole Table
CREATE TABLE [JOB_ROLE] (
	[JOB_ROLE_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_JOB_ROLE PRIMARY KEY,
	[JOB_TITLE] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For Permisisons Table
CREATE TABLE [PERMISSION] (
	[PERMISSION_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_PERMISSION PRIMARY KEY,
	[VIEW] [bit] NOT NULL,
	[EDIT] [bit] NOT NULL,
	[ADD] [bit] NOT NULL,
	[DELETE] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For JobRole_Permissions Bridge Table
CREATE TABLE [JOB_ROLE_PERMISSION] (
	[FK_JOB_ROLE_ID] [int] NOT NULL,
	[FK_PERMISSION_ID] [int] NOT NULL,
	CONSTRAINT PK_JOB_ROLE_PERMISSION PRIMARY KEY ([FK_JOB_ROLE_ID], [FK_PERMISSION_ID])
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For ExpenseType Table
CREATE TABLE [EXPENSE_TYPE] (
	[EXPENSE_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_EXPENSE_TYPE PRIMARY KEY,
	[EXPENSE_TITLE] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For ReportLog Table
CREATE TABLE [REPORT_LOG] (
	[REPORT_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_REPORT_LOG PRIMARY KEY,
	[REPORT_TYPE] [varchar](50) NOT NULL,
	[FK_GENERATED_BY] [int] NULL,
	[GENERATION_DATE] [datetime] NOT NULL,
	[START_DATE] [datetime] NOT NULL,
	[END_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For Category Table
CREATE TABLE [CATEGORY] (
	[CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_CATEGORY PRIMARY KEY,
	[CATEGORY_NAME] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For Subcategory Table
CREATE TABLE [SUB_CATEGORY] (
	[SUB_CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_SUB_CATEGORY PRIMARY KEY,
	[SUB_CATEGORY_NAME] [varchar](50) NOT NULL,
	[FK_CATEGORY_ID] [int] NULL,
	[FK_EXPENSE_ID] [int] NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- For PaymentMethod Table
CREATE TABLE [PAYMENT_METHOD] (
	[PAYMENT_METHOD_ID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY,
	[PAYMENT_METHOD_NAME] [varchar] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- ADDING FOREIGN KEYS

-- User table
ALTER TABLE [USER]  WITH CHECK ADD FOREIGN KEY([FK_JOB_ROLE_ID])
REFERENCES [JOB_ROLE] ([JOB_ROLE_ID])
ON DELETE SET NULL
GO

-- User Account table
ALTER TABLE [USER_ACCOUNT]  WITH CHECK ADD FOREIGN KEY([FK_USER_ID])
REFERENCES [USER] ([USER_ID])
ON DELETE CASCADE
GO

ALTER TABLE [USER_ACCOUNT]  WITH CHECK ADD FOREIGN KEY([FK_ACCOUNT_ID])
REFERENCES [ACCOUNT] ([ACCOUNT_ID])
ON DELETE CASCADE
GO

-- Transaction table
ALTER TABLE [TRANSACTION]  WITH CHECK ADD FOREIGN KEY([FK_PAYMENT_METHOD_ID])
REFERENCES [PAYMENT_METHOD] ([PAYMENT_METHOD_ID])
ON DELETE SET NULL
GO

ALTER TABLE [TRANSACTION]  WITH CHECK ADD FOREIGN KEY([FK_ACCOUNT_ID])
REFERENCES [ACCOUNT] ([ACCOUNT_ID])
ON DELETE SET NULL
GO

ALTER TABLE [TRANSACTION]  WITH CHECK ADD FOREIGN KEY([FK_EXPENSE_ID])
REFERENCES [EXPENSE_TYPE] ([EXPENSE_ID])
ON DELETE SET NULL
GO

ALTER TABLE [TRANSACTION]  WITH CHECK ADD FOREIGN KEY([FK_CREATED_BY])
REFERENCES [USER] ([USER_ID])
ON DELETE SET NULL
GO

ALTER TABLE [TRANSACTION]  WITH CHECK ADD FOREIGN KEY([FK_LAST_UPDATED_BY])
REFERENCES [USER] ([USER_ID])
ON DELETE SET NULL
GO

-- JobRole_Permission Table
ALTER TABLE [JOB_ROLE_PERMISSION]  WITH CHECK ADD FOREIGN KEY([FK_JOB_ROLE_ID])
REFERENCES [JOB_ROLE] ([JOB_ROLE_ID])
ON DELETE CASCADE
GO

ALTER TABLE [JOB_ROLE_PERMISSION]  WITH CHECK ADD FOREIGN KEY([FK_PERMISSION_ID])
REFERENCES [PERMISSION] ([PERMISSION_ID])
ON DELETE CASCADE
GO

-- Report Log
ALTER TABLE [REPORT_LOG]  WITH CHECK ADD FOREIGN KEY([FK_GENERATED_BY])
REFERENCES [USER] ([USER_ID])
ON DELETE SET NULL
GO

-- Subcategory
ALTER TABLE [SUB_CATEGORY]  WITH CHECK ADD FOREIGN KEY([FK_CATEGORY_ID])
REFERENCES [CATEGORY] ([CATEGORY_ID])
ON DELETE SET NULL -- SHOULD IT BE NULL OR CASCADE?
GO

ALTER TABLE [SUB_CATEGORY]  WITH CHECK ADD FOREIGN KEY([FK_EXPENSE_ID])
REFERENCES [EXPENSE_TYPE] ([EXPENSE_ID])
ON DELETE SET NULL
GO